version: '3.8'

services:
  db:
    image: postgres:13.16-bookworm
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"    # Maps container port 5432 to host port 5432

volumes:
  postgres_data: